/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ConfidentifyAccountCreateRequest,
    ConfidentifyAccountCreateRequestFromJSON,
    ConfidentifyAccountCreateRequestToJSON,
    ConfidentifyAccountResponse,
    ConfidentifyAccountResponseFromJSON,
    ConfidentifyAccountResponseToJSON,
    ConfidentifyAccountUpdateRequest,
    ConfidentifyAccountUpdateRequestFromJSON,
    ConfidentifyAccountUpdateRequestToJSON,
    ConfidentifyUserResponse,
    ConfidentifyUserResponseFromJSON,
    ConfidentifyUserResponseToJSON,
    ConfidentifyUserUpdateRequest,
    ConfidentifyUserUpdateRequestFromJSON,
    ConfidentifyUserUpdateRequestToJSON,
} from '../models';

export interface AccountByIdGetRequest {
    accountId: string;
}

export interface AccountByIdUpdateRequest {
    accountId: string;
    confidentifyAccountUpdateRequest?: ConfidentifyAccountUpdateRequest;
}

export interface AccountCreateRequest {
    confidentifyAccountCreateRequest?: ConfidentifyAccountCreateRequest;
}

export interface UserByIdGetRequest {
    accountId: string;
    username: string;
}

export interface UserByIdUpdateRequest {
    accountId: string;
    username: string;
    confidentifyUserUpdateRequest?: ConfidentifyUserUpdateRequest;
}

/**
 * no description
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Get account information
     */
    async accountByIdGetRaw(requestParameters: AccountByIdGetRequest): Promise<runtime.ApiResponse<ConfidentifyAccountResponse>> {
        if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
            throw new runtime.RequiredError('accountId','Required parameter requestParameters.accountId was null or undefined when calling accountByIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("oAuth2ClientCredentials", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/accounts/{account_id}`.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters.accountId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfidentifyAccountResponseFromJSON(jsonValue));
    }

    /**
     * Get account information
     */
    async accountByIdGet(requestParameters: AccountByIdGetRequest): Promise<ConfidentifyAccountResponse> {
        const response = await this.accountByIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update account information
     */
    async accountByIdUpdateRaw(requestParameters: AccountByIdUpdateRequest): Promise<runtime.ApiResponse<ConfidentifyAccountResponse>> {
        if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
            throw new runtime.RequiredError('accountId','Required parameter requestParameters.accountId was null or undefined when calling accountByIdUpdate.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("oAuth2ClientCredentials", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/accounts/{account_id}`.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters.accountId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfidentifyAccountUpdateRequestToJSON(requestParameters.confidentifyAccountUpdateRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfidentifyAccountResponseFromJSON(jsonValue));
    }

    /**
     * Update account information
     */
    async accountByIdUpdate(requestParameters: AccountByIdUpdateRequest): Promise<ConfidentifyAccountResponse> {
        const response = await this.accountByIdUpdateRaw(requestParameters);
        return await response.value();
    }

    /**
     * Create new account
     */
    async accountCreateRaw(requestParameters: AccountCreateRequest): Promise<runtime.ApiResponse<ConfidentifyAccountResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("oAuth2ClientCredentials", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/accounts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfidentifyAccountCreateRequestToJSON(requestParameters.confidentifyAccountCreateRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfidentifyAccountResponseFromJSON(jsonValue));
    }

    /**
     * Create new account
     */
    async accountCreate(requestParameters: AccountCreateRequest): Promise<ConfidentifyAccountResponse> {
        const response = await this.accountCreateRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get user information
     */
    async userByIdGetRaw(requestParameters: UserByIdGetRequest): Promise<runtime.ApiResponse<ConfidentifyUserResponse>> {
        if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
            throw new runtime.RequiredError('accountId','Required parameter requestParameters.accountId was null or undefined when calling userByIdGet.');
        }

        if (requestParameters.username === null || requestParameters.username === undefined) {
            throw new runtime.RequiredError('username','Required parameter requestParameters.username was null or undefined when calling userByIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("oAuth2ClientCredentials", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/accounts/{account_id}/users/{username}`.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters.accountId))).replace(`{${"username"}}`, encodeURIComponent(String(requestParameters.username))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfidentifyUserResponseFromJSON(jsonValue));
    }

    /**
     * Get user information
     */
    async userByIdGet(requestParameters: UserByIdGetRequest): Promise<ConfidentifyUserResponse> {
        const response = await this.userByIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update user information
     */
    async userByIdUpdateRaw(requestParameters: UserByIdUpdateRequest): Promise<runtime.ApiResponse<ConfidentifyUserResponse>> {
        if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
            throw new runtime.RequiredError('accountId','Required parameter requestParameters.accountId was null or undefined when calling userByIdUpdate.');
        }

        if (requestParameters.username === null || requestParameters.username === undefined) {
            throw new runtime.RequiredError('username','Required parameter requestParameters.username was null or undefined when calling userByIdUpdate.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("oAuth2ClientCredentials", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/accounts/{account_id}/users/{username}`.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters.accountId))).replace(`{${"username"}}`, encodeURIComponent(String(requestParameters.username))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfidentifyUserUpdateRequestToJSON(requestParameters.confidentifyUserUpdateRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfidentifyUserResponseFromJSON(jsonValue));
    }

    /**
     * Update user information
     */
    async userByIdUpdate(requestParameters: UserByIdUpdateRequest): Promise<ConfidentifyUserResponse> {
        const response = await this.userByIdUpdateRaw(requestParameters);
        return await response.value();
    }

}
