/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AuthRequest,
    AuthRequestFromJSON,
    AuthRequestToJSON,
    AuthResponse,
    AuthResponseFromJSON,
    AuthResponseToJSON,
} from '../models';

export interface AuthPostRequest {
    authRequest: AuthRequest;
}

/**
 * no description
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Consuming username/password or other credential types, this endpoint issues access tokens to be provided for the `Authorization` header of other endpoints. Access tokens are valid for 5 minutes. 
     * Authenticate credentials and retrieve an access token.
     */
    async authPostRaw(requestParameters: AuthPostRequest): Promise<runtime.ApiResponse<AuthResponse>> {
        if (requestParameters.authRequest === null || requestParameters.authRequest === undefined) {
            throw new runtime.RequiredError('authRequest','Required parameter requestParameters.authRequest was null or undefined when calling authPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("oAuth2ClientCredentials", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/auth`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthRequestToJSON(requestParameters.authRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * Consuming username/password or other credential types, this endpoint issues access tokens to be provided for the `Authorization` header of other endpoints. Access tokens are valid for 5 minutes. 
     * Authenticate credentials and retrieve an access token.
     */
    async authPost(requestParameters: AuthPostRequest): Promise<AuthResponse> {
        const response = await this.authPostRaw(requestParameters);
        return await response.value();
    }

}
