/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorizationCodeRequest
 */
export interface AuthorizationCodeRequest {
    /**
     * The OAuth2 counterpart\'s identifier.
     * @type {string}
     * @memberof AuthorizationCodeRequest
     */
    clientId?: string;
    /**
     * Base redirect URL provided by the counterpart.
     * @type {string}
     * @memberof AuthorizationCodeRequest
     */
    redirectUri?: string;
    /**
     * State variable generated by the OAuth2 counterpart.
     * @type {string}
     * @memberof AuthorizationCodeRequest
     */
    state?: string;
}

export function AuthorizationCodeRequestFromJSON(json: any): AuthorizationCodeRequest {
    return AuthorizationCodeRequestFromJSONTyped(json, false);
}

export function AuthorizationCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizationCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientId': !exists(json, 'client_id') ? undefined : json['client_id'],
        'redirectUri': !exists(json, 'redirect_uri') ? undefined : json['redirect_uri'],
        'state': !exists(json, 'state') ? undefined : json['state'],
    };
}

export function AuthorizationCodeRequestToJSON(value?: AuthorizationCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client_id': value.clientId,
        'redirect_uri': value.redirectUri,
        'state': value.state,
    };
}


