/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfidentifyUserResponse
 */
export interface ConfidentifyUserResponse {
    /**
     * 
     * @type {string}
     * @memberof ConfidentifyUserResponse
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfidentifyUserResponse
     */
    accountId?: string;
    /**
     * A running approximate count of how many times the user has logged in.
     * @type {number}
     * @memberof ConfidentifyUserResponse
     */
    loginCount?: number;
    /**
     * The time of the user\'s last login
     * @type {Date}
     * @memberof ConfidentifyUserResponse
     */
    loginAt?: Date;
    /**
     * The user\'s name
     * @type {string}
     * @memberof ConfidentifyUserResponse
     */
    name?: string;
    /**
     * The user\'s profile image
     * @type {string}
     * @memberof ConfidentifyUserResponse
     */
    imageUrl?: string;
    /**
     * The user\'s email
     * @type {string}
     * @memberof ConfidentifyUserResponse
     */
    email?: string;
}

export function ConfidentifyUserResponseFromJSON(json: any): ConfidentifyUserResponse {
    return ConfidentifyUserResponseFromJSONTyped(json, false);
}

export function ConfidentifyUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfidentifyUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
        'loginCount': !exists(json, 'login_count') ? undefined : json['login_count'],
        'loginAt': !exists(json, 'login_at') ? undefined : (new Date(json['login_at'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function ConfidentifyUserResponseToJSON(value?: ConfidentifyUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'account_id': value.accountId,
        'login_count': value.loginCount,
        'login_at': value.loginAt === undefined ? undefined : (value.loginAt.toISOString()),
        'name': value.name,
        'image_url': value.imageUrl,
        'email': value.email,
    };
}


