/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DatasetStats,
    DatasetStatsFromJSON,
    DatasetStatsFromJSONTyped,
    DatasetStatsToJSON,
} from './';

/**
 * 
 * @export
 * @interface DatasetAllAllOf
 */
export interface DatasetAllAllOf {
    /**
     * 
     * @type {DatasetStats}
     * @memberof DatasetAllAllOf
     */
    stats?: DatasetStats;
    /**
     * The time of creation of the dataset
     * @type {Date}
     * @memberof DatasetAllAllOf
     */
    createdAt?: Date;
    /**
     * The username of the user who created the dataset
     * @type {string}
     * @memberof DatasetAllAllOf
     */
    createdBy?: string;
}

export function DatasetAllAllOfFromJSON(json: any): DatasetAllAllOf {
    return DatasetAllAllOfFromJSONTyped(json, false);
}

export function DatasetAllAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetAllAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stats': !exists(json, 'stats') ? undefined : DatasetStatsFromJSON(json['stats']),
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
    };
}

export function DatasetAllAllOfToJSON(value?: DatasetAllAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stats': DatasetStatsToJSON(value.stats),
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'created_by': value.createdBy,
    };
}


