/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DatasetAllAllOf,
    DatasetAllAllOfFromJSON,
    DatasetAllAllOfFromJSONTyped,
    DatasetAllAllOfToJSON,
    DatasetListItem,
    DatasetListItemFromJSON,
    DatasetListItemFromJSONTyped,
    DatasetListItemToJSON,
    DatasetSchema,
    DatasetSchemaFromJSON,
    DatasetSchemaFromJSONTyped,
    DatasetSchemaToJSON,
    DatasetStats,
    DatasetStatsFromJSON,
    DatasetStatsFromJSONTyped,
    DatasetStatsToJSON,
} from './';

/**
 * 
 * @export
 * @interface DatasetAll
 */
export interface DatasetAll {
    /**
     * The name of the dataset
     * @type {string}
     * @memberof DatasetAll
     */
    name?: string;
    /**
     * 
     * @type {DatasetSchema}
     * @memberof DatasetAll
     */
    schema?: DatasetSchema;
    /**
     * The unique ID of the dataset
     * @type {string}
     * @memberof DatasetAll
     */
    id?: string;
    /**
     * The HTTP path to the dataset
     * @type {string}
     * @memberof DatasetAll
     */
    href?: string;
    /**
     * 
     * @type {DatasetStats}
     * @memberof DatasetAll
     */
    stats?: DatasetStats;
    /**
     * The time of creation of the dataset
     * @type {Date}
     * @memberof DatasetAll
     */
    createdAt?: Date;
    /**
     * The username of the user who created the dataset
     * @type {string}
     * @memberof DatasetAll
     */
    createdBy?: string;
}

export function DatasetAllFromJSON(json: any): DatasetAll {
    return DatasetAllFromJSONTyped(json, false);
}

export function DatasetAllFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetAll {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'schema': !exists(json, 'schema') ? undefined : DatasetSchemaFromJSON(json['schema']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'href': !exists(json, 'href') ? undefined : json['href'],
        'stats': !exists(json, 'stats') ? undefined : DatasetStatsFromJSON(json['stats']),
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
    };
}

export function DatasetAllToJSON(value?: DatasetAll | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'schema': DatasetSchemaToJSON(value.schema),
        'id': value.id,
        'href': value.href,
        'stats': DatasetStatsToJSON(value.stats),
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'created_by': value.createdBy,
    };
}


