/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DatasetRecordAllAllOf,
    DatasetRecordAllAllOfFromJSON,
    DatasetRecordAllAllOfFromJSONTyped,
    DatasetRecordAllAllOfToJSON,
    DatasetRecordBase,
    DatasetRecordBaseFromJSON,
    DatasetRecordBaseFromJSONTyped,
    DatasetRecordBaseToJSON,
} from './';

/**
 * 
 * @export
 * @interface DatasetRecordAll
 */
export interface DatasetRecordAll {
    /**
     * A unique ID for the record 
     * @type {string}
     * @memberof DatasetRecordAll
     */
    id?: string;
    /**
     * The record\'s data with keys matching the properties defined in the dataset\'s `schema` 
     * @type {object}
     * @memberof DatasetRecordAll
     */
    entity?: object;
    /**
     * A string which identifies the source of the record. 
     * @type {string}
     * @memberof DatasetRecordAll
     */
    recordSource?: string;
    /**
     * The time of creation of the record
     * @type {Date}
     * @memberof DatasetRecordAll
     */
    createdAt?: Date;
}

export function DatasetRecordAllFromJSON(json: any): DatasetRecordAll {
    return DatasetRecordAllFromJSONTyped(json, false);
}

export function DatasetRecordAllFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetRecordAll {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'entity': !exists(json, 'entity') ? undefined : json['entity'],
        'recordSource': !exists(json, 'record_source') ? undefined : json['record_source'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function DatasetRecordAllToJSON(value?: DatasetRecordAll | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'entity': value.entity,
        'record_source': value.recordSource,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}


