/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DedupJobBaseResults,
    DedupJobBaseResultsFromJSON,
    DedupJobBaseResultsFromJSONTyped,
    DedupJobBaseResultsToJSON,
} from './';

/**
 * 
 * @export
 * @interface DedupJobBase
 */
export interface DedupJobBase {
    /**
     * A unique ID for the deduplication job 
     * @type {string}
     * @memberof DedupJobBase
     */
    id?: string;
    /**
     * An optional name for the job 
     * @type {string}
     * @memberof DedupJobBase
     */
    name?: string;
    /**
     * Determines if the job is currently running.
     * @type {boolean}
     * @memberof DedupJobBase
     */
    running?: boolean;
    /**
     * The date and time of job creation.
     * @type {Date}
     * @memberof DedupJobBase
     */
    createdAt?: Date;
    /**
     * 
     * @type {DedupJobBaseResults}
     * @memberof DedupJobBase
     */
    results?: DedupJobBaseResults;
}

export function DedupJobBaseFromJSON(json: any): DedupJobBase {
    return DedupJobBaseFromJSONTyped(json, false);
}

export function DedupJobBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DedupJobBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'running': !exists(json, 'running') ? undefined : json['running'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'results': !exists(json, 'results') ? undefined : DedupJobBaseResultsFromJSON(json['results']),
    };
}

export function DedupJobBaseToJSON(value?: DedupJobBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'running': value.running,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'results': DedupJobBaseResultsToJSON(value.results),
    };
}


