/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DedupJobAllAllOf,
    DedupJobAllAllOfFromJSON,
    DedupJobAllAllOfFromJSONTyped,
    DedupJobAllAllOfToJSON,
    DedupJobAllAllOfResults,
    DedupJobAllAllOfResultsFromJSON,
    DedupJobAllAllOfResultsFromJSONTyped,
    DedupJobAllAllOfResultsToJSON,
    DedupJobBase,
    DedupJobBaseFromJSON,
    DedupJobBaseFromJSONTyped,
    DedupJobBaseToJSON,
} from './';

/**
 * 
 * @export
 * @interface DedupJobAll
 */
export interface DedupJobAll {
    /**
     * A unique ID for the deduplication job 
     * @type {string}
     * @memberof DedupJobAll
     */
    id?: string;
    /**
     * Determines if the job is currently running.
     * @type {boolean}
     * @memberof DedupJobAll
     */
    running?: boolean;
    /**
     * The date and time of job creation.
     * @type {Date}
     * @memberof DedupJobAll
     */
    createdAt?: Date;
    /**
     * The ID of the dataset that the deduplication job is targeting.
     * @type {string}
     * @memberof DedupJobAll
     */
    datasetId?: string;
    /**
     * The date and time of job starting.
     * @type {Date}
     * @memberof DedupJobAll
     */
    startedAt?: Date;
    /**
     * The date and time of job finishing.
     * @type {Date}
     * @memberof DedupJobAll
     */
    finishedAt?: Date;
    /**
     * A description of the latest known job state.
     * @type {string}
     * @memberof DedupJobAll
     */
    phase?: string;
    /**
     * 
     * @type {DedupJobAllAllOfResults}
     * @memberof DedupJobAll
     */
    results?: DedupJobAllAllOfResults;
}

export function DedupJobAllFromJSON(json: any): DedupJobAll {
    return DedupJobAllFromJSONTyped(json, false);
}

export function DedupJobAllFromJSONTyped(json: any, ignoreDiscriminator: boolean): DedupJobAll {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'running': !exists(json, 'running') ? undefined : json['running'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'datasetId': !exists(json, 'dataset_id') ? undefined : json['dataset_id'],
        'startedAt': !exists(json, 'started_at') ? undefined : (new Date(json['started_at'])),
        'finishedAt': !exists(json, 'finished_at') ? undefined : (new Date(json['finished_at'])),
        'phase': !exists(json, 'phase') ? undefined : json['phase'],
        'results': !exists(json, 'results') ? undefined : DedupJobAllAllOfResultsFromJSON(json['results']),
    };
}

export function DedupJobAllToJSON(value?: DedupJobAll | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'running': value.running,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'dataset_id': value.datasetId,
        'started_at': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'finished_at': value.finishedAt === undefined ? undefined : (value.finishedAt.toISOString()),
        'phase': value.phase,
        'results': DedupJobAllAllOfResultsToJSON(value.results),
    };
}


