/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DedupJobAllAllOfProgress,
    DedupJobAllAllOfProgressFromJSON,
    DedupJobAllAllOfProgressFromJSONTyped,
    DedupJobAllAllOfProgressToJSON,
    DedupJobAllAllOfResults,
    DedupJobAllAllOfResultsFromJSON,
    DedupJobAllAllOfResultsFromJSONTyped,
    DedupJobAllAllOfResultsToJSON,
} from './';

/**
 * 
 * @export
 * @interface DedupJobAllAllOf
 */
export interface DedupJobAllAllOf {
    /**
     * The ID of the dataset that the deduplication job is targeting.
     * @type {string}
     * @memberof DedupJobAllAllOf
     */
    datasetId?: string;
    /**
     * The date and time of job starting.
     * @type {Date}
     * @memberof DedupJobAllAllOf
     */
    startedAt?: Date;
    /**
     * The date and time of job finishing.
     * @type {Date}
     * @memberof DedupJobAllAllOf
     */
    finishedAt?: Date;
    /**
     * A description of the latest known job state.
     * @type {string}
     * @memberof DedupJobAllAllOf
     */
    phase?: string;
    /**
     * 
     * @type {DedupJobAllAllOfProgress}
     * @memberof DedupJobAllAllOf
     */
    progress?: DedupJobAllAllOfProgress;
    /**
     * 
     * @type {DedupJobAllAllOfResults}
     * @memberof DedupJobAllAllOf
     */
    results?: DedupJobAllAllOfResults;
}

export function DedupJobAllAllOfFromJSON(json: any): DedupJobAllAllOf {
    return DedupJobAllAllOfFromJSONTyped(json, false);
}

export function DedupJobAllAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DedupJobAllAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasetId': !exists(json, 'dataset_id') ? undefined : json['dataset_id'],
        'startedAt': !exists(json, 'started_at') ? undefined : (new Date(json['started_at'])),
        'finishedAt': !exists(json, 'finished_at') ? undefined : (new Date(json['finished_at'])),
        'phase': !exists(json, 'phase') ? undefined : json['phase'],
        'progress': !exists(json, 'progress') ? undefined : DedupJobAllAllOfProgressFromJSON(json['progress']),
        'results': !exists(json, 'results') ? undefined : DedupJobAllAllOfResultsFromJSON(json['results']),
    };
}

export function DedupJobAllAllOfToJSON(value?: DedupJobAllAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataset_id': value.datasetId,
        'started_at': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'finished_at': value.finishedAt === undefined ? undefined : (value.finishedAt.toISOString()),
        'phase': value.phase,
        'progress': DedupJobAllAllOfProgressToJSON(value.progress),
        'results': DedupJobAllAllOfResultsToJSON(value.results),
    };
}


