/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdentifyResponseRecordEntity,
    IdentifyResponseRecordEntityFromJSON,
    IdentifyResponseRecordEntityFromJSONTyped,
    IdentifyResponseRecordEntityToJSON,
} from './';

/**
 * 
 * @export
 * @interface IdentifyResponseRecord
 */
export interface IdentifyResponseRecord {
    /**
     * 
     * @type {string}
     * @memberof IdentifyResponseRecord
     */
    id?: string;
    /**
     * 
     * @type {Array<IdentifyResponseRecordEntity>}
     * @memberof IdentifyResponseRecord
     */
    entities?: Array<IdentifyResponseRecordEntity>;
}

export function IdentifyResponseRecordFromJSON(json: any): IdentifyResponseRecord {
    return IdentifyResponseRecordFromJSONTyped(json, false);
}

export function IdentifyResponseRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentifyResponseRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'entities': !exists(json, 'entities') ? undefined : ((json['entities'] as Array<any>).map(IdentifyResponseRecordEntityFromJSON)),
    };
}

export function IdentifyResponseRecordToJSON(value?: IdentifyResponseRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'entities': value.entities === undefined ? undefined : ((value.entities as Array<any>).map(IdentifyResponseRecordEntityToJSON)),
    };
}


