/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestFileResponseUploadTo
 */
export interface IngestFileResponseUploadTo {
    /**
     * The URL to upload the file contents to.
     * @type {string}
     * @memberof IngestFileResponseUploadTo
     */
    url?: string;
    /**
     * The HTTP method to use when uploading the file contents. This will always be `PUT`.
     * @type {string}
     * @memberof IngestFileResponseUploadTo
     */
    httpMethod?: string;
}

export function IngestFileResponseUploadToFromJSON(json: any): IngestFileResponseUploadTo {
    return IngestFileResponseUploadToFromJSONTyped(json, false);
}

export function IngestFileResponseUploadToFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestFileResponseUploadTo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'httpMethod': !exists(json, 'http_method') ? undefined : json['http_method'],
    };
}

export function IngestFileResponseUploadToToJSON(value?: IngestFileResponseUploadTo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'http_method': value.httpMethod,
    };
}


