/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MatchJobBase,
    MatchJobBaseFromJSON,
    MatchJobBaseFromJSONTyped,
    MatchJobBaseToJSON,
    NextPageInformation,
    NextPageInformationFromJSON,
    NextPageInformationFromJSONTyped,
    NextPageInformationToJSON,
} from './';

/**
 * 
 * @export
 * @interface MatchJobsQueryResponse
 */
export interface MatchJobsQueryResponse {
    /**
     * The jobs retrieved from the query 
     * @type {Array<MatchJobBase>}
     * @memberof MatchJobsQueryResponse
     */
    jobs?: Array<MatchJobBase>;
    /**
     * 
     * @type {NextPageInformation}
     * @memberof MatchJobsQueryResponse
     */
    nextPage?: NextPageInformation;
}

export function MatchJobsQueryResponseFromJSON(json: any): MatchJobsQueryResponse {
    return MatchJobsQueryResponseFromJSONTyped(json, false);
}

export function MatchJobsQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchJobsQueryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobs': !exists(json, 'jobs') ? undefined : ((json['jobs'] as Array<any>).map(MatchJobBaseFromJSON)),
        'nextPage': !exists(json, 'next_page') ? undefined : NextPageInformationFromJSON(json['next_page']),
    };
}

export function MatchJobsQueryResponseToJSON(value?: MatchJobsQueryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jobs': value.jobs === undefined ? undefined : ((value.jobs as Array<any>).map(MatchJobBaseToJSON)),
        'next_page': NextPageInformationToJSON(value.nextPage),
    };
}


