/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Provides the results of the job. If the job is still running, there may still be preliminary results available.
 * @export
 * @interface MatchJobBaseResults
 */
export interface MatchJobBaseResults {
    /**
     * Number of record pairs matched with a \'matched\' verdict.
     * @type {number}
     * @memberof MatchJobBaseResults
     */
    pairsMatched?: number;
    /**
     * Number of record pairs matched with a \'questionable\' verdict.
     * @type {number}
     * @memberof MatchJobBaseResults
     */
    pairsQuestionable?: number;
}

export function MatchJobBaseResultsFromJSON(json: any): MatchJobBaseResults {
    return MatchJobBaseResultsFromJSONTyped(json, false);
}

export function MatchJobBaseResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchJobBaseResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pairsMatched': !exists(json, 'pairs_matched') ? undefined : json['pairs_matched'],
        'pairsQuestionable': !exists(json, 'pairs_questionable') ? undefined : json['pairs_questionable'],
    };
}

export function MatchJobBaseResultsToJSON(value?: MatchJobBaseResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pairs_matched': value.pairsMatched,
        'pairs_questionable': value.pairsQuestionable,
    };
}


