/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NextPageInformation
 */
export interface NextPageInformation {
    /**
     * Provides a link to the next page of data
     * @type {string}
     * @memberof NextPageInformation
     */
    url?: string;
    /**
     * Provides the raw value for the `page[size]` parameter, for clients that prefer to build the paging URL themselves.
     * @type {number}
     * @memberof NextPageInformation
     */
    paramPageSize?: number;
    /**
     * Provides the raw value for the `page[after]` parameter, for clients that prefer to build the paging URL themselves.
     * @type {string}
     * @memberof NextPageInformation
     */
    paramPageAfter?: string;
}

export function NextPageInformationFromJSON(json: any): NextPageInformation {
    return NextPageInformationFromJSONTyped(json, false);
}

export function NextPageInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): NextPageInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'paramPageSize': !exists(json, 'param_page_size') ? undefined : json['param_page_size'],
        'paramPageAfter': !exists(json, 'param_page_after') ? undefined : json['param_page_after'],
    };
}

export function NextPageInformationToJSON(value?: NextPageInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'param_page_size': value.paramPageSize,
        'param_page_after': value.paramPageAfter,
    };
}


