/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    PersonNameDetailsRequestRecord,
    PersonNameFullNameRequestRecord,
    PersonNameDetailsRequestRecordFromJSONTyped,
    PersonNameDetailsRequestRecordToJSON,
    PersonNameFullNameRequestRecordFromJSONTyped,
    PersonNameFullNameRequestRecordToJSON,
} from './';

/**
 * @type PersonNameRequestRecord
 * @export
 */
export type PersonNameRequestRecord = PersonNameDetailsRequestRecord | PersonNameFullNameRequestRecord;

export function PersonNameRequestRecordFromJSON(json: any): PersonNameRequestRecord {
    return PersonNameRequestRecordFromJSONTyped(json, false);
}

export function PersonNameRequestRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonNameRequestRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...PersonNameDetailsRequestRecordFromJSONTyped(json, true), ...PersonNameFullNameRequestRecordFromJSONTyped(json, true) };
}

export function PersonNameRequestRecordToJSON(value?: PersonNameRequestRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...PersonNameDetailsRequestRecordToJSON(value), ...PersonNameFullNameRequestRecordToJSON(value) };
}

