/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DatasetRecordBase,
    DatasetRecordBaseFromJSON,
    DatasetRecordBaseFromJSONTyped,
    DatasetRecordBaseToJSON,
    RecordsQueryResponseNextPage,
    RecordsQueryResponseNextPageFromJSON,
    RecordsQueryResponseNextPageFromJSONTyped,
    RecordsQueryResponseNextPageToJSON,
} from './';

/**
 * 
 * @export
 * @interface RecordsQueryResponse
 */
export interface RecordsQueryResponse {
    /**
     * The records retrieved from the query, each represented as an object with keys matching the properties defined in the dataset\'s `schema`. 
     * @type {Array<DatasetRecordBase>}
     * @memberof RecordsQueryResponse
     */
    records?: Array<DatasetRecordBase>;
    /**
     * 
     * @type {RecordsQueryResponseNextPage}
     * @memberof RecordsQueryResponse
     */
    nextPage?: RecordsQueryResponseNextPage;
}

export function RecordsQueryResponseFromJSON(json: any): RecordsQueryResponse {
    return RecordsQueryResponseFromJSONTyped(json, false);
}

export function RecordsQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordsQueryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(DatasetRecordBaseFromJSON)),
        'nextPage': !exists(json, 'next_page') ? undefined : RecordsQueryResponseNextPageFromJSON(json['next_page']),
    };
}

export function RecordsQueryResponseToJSON(value?: RecordsQueryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(DatasetRecordBaseToJSON)),
        'next_page': RecordsQueryResponseNextPageToJSON(value.nextPage),
    };
}


