/* tslint:disable */
/* eslint-disable */
/**
 * Confidentify API
 * Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProcessorVerdict,
    ProcessorVerdictFromJSON,
    ProcessorVerdictFromJSONTyped,
    ProcessorVerdictToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProcessorOutcome
 */
export interface ProcessorOutcome {
    /**
     * 
     * @type {ProcessorVerdict}
     * @memberof ProcessorOutcome
     */
    verdict?: ProcessorVerdict;
    /**
     * A list of informational entries about the processed entity.
     * @type {Array<string>}
     * @memberof ProcessorOutcome
     */
    info?: Array<string>;
    /**
     * A list of warnings about the processed entity.
     * @type {Array<string>}
     * @memberof ProcessorOutcome
     */
    warn?: Array<string>;
}

export function ProcessorOutcomeFromJSON(json: any): ProcessorOutcome {
    return ProcessorOutcomeFromJSONTyped(json, false);
}

export function ProcessorOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessorOutcome {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'verdict': !exists(json, 'verdict') ? undefined : ProcessorVerdictFromJSON(json['verdict']),
        'info': !exists(json, 'info') ? undefined : json['info'],
        'warn': !exists(json, 'warn') ? undefined : json['warn'],
    };
}

export function ProcessorOutcomeToJSON(value?: ProcessorOutcome | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'verdict': ProcessorVerdictToJSON(value.verdict),
        'info': value.info,
        'warn': value.warn,
    };
}


